"""Add performance indexes

Revision ID: 002
Revises: 001
Create Date: 2026-02-04 21:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '002'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add composite index for contracts list queries
    op.create_index(
        'ix_contracts_user_id_created_at',
        'contracts',
        ['user_id', 'created_at'],
        postgresql_using='btree',
    )
    
    # Add index on contract status for filtering
    op.create_index(
        'ix_contracts_status',
        'contracts',
        ['status'],
        postgresql_using='btree',
    )
    
    # Add composite index for user + status queries
    op.create_index(
        'ix_contracts_user_id_status',
        'contracts',
        ['user_id', 'status'],
        postgresql_using='btree',
    )
    
    # Add index on analysis status
    op.create_index(
        'ix_analyses_status',
        'analyses',
        ['status'],
        postgresql_using='btree',
    )
    
    # Add composite index for analysis queries with contract
    op.create_index(
        'ix_analyses_contract_id_status',
        'analyses',
        ['contract_id', 'status'],
        postgresql_using='btree',
    )
    
    # Add index on created_at for time-based queries
    op.create_index(
        'ix_contracts_created_at',
        'contracts',
        ['created_at'],
        postgresql_using='btree',
    )
    
    op.create_index(
        'ix_analyses_created_at',
        'analyses',
        ['created_at'],
        postgresql_using='btree',
    )
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_contracts_user_id_created_at')
    op.drop_index('ix_contracts_status')
    op.drop_index('ix_contracts_user_id_status')
    op.drop_index('ix_analyses_status')
    op.drop_index('ix_analyses_contract_id_status')
    op.drop_index('ix_contracts_created_at')
    op.drop_index('ix_analyses_created_at')
    # ### end Alembic commands ###
